name: Deploy to dev
on:
  push:
    branches:
      - main
jobs:
  environment: pipeline-test-env
  migrate-and-deploy:
    uses: ./.github/workflows/migrate-and-deploy.yaml
    with:
      organization-id: c0758a52-37d2-4245-a017-870e1d1f66a4
      environment-id: b0e7ae45-1b94-4b0e-9fd6-448ca6a2313e
      application-ids: 36d8ab5b-92e2-4470-a566-e0677d824c02
    secrets:
      api-token: ${{ secrets.QOVERY_API_TOKEN }}
      db-connection-string: ${{ secrets.DB_CONNECTION_STRING }}