name: Deploy to dev
on:
  push:
    branches:
      - main
jobs:
  test-and-deploy:
    uses: ./.github/workflows/test-and-deploy.yaml
    with:
      organization-id: c0758a52-37d2-4245-a017-870e1d1f66a4
      environment-id: 44b4b80f-b998-4724-8ef6-ea0e9925aada
      application-ids: 745dcc45-4f3c-4c66-96dd-bc8603eb1b22
    secrets:
      api-token: ${{ secrets.QOVERY_API_TOKEN }}