name: Migrate and Deploy on Qovery
on:
  workflow_call:
    inputs:
      organization-id:
        required: true
        type: string
      environment-id:
        required: true
        type: string
      application-ids:
        required: true
        type: string
    secrets:
      api-token:
        required: true
jobs:
  migrate:
    environment: pipeline-test-env
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install EF
        run: dotnet tool install --global dotnet-ef
      - name: Run Migration
        run: dotnet ef database update --project RecipeManagement/src/RecipeManagement
        with:
          DB_CONNECTION_STRING: ${{ secrets.db-connection-string }}
  deploy:
    needs: migrate
    runs-on: ubuntu-latest
    name: Deploy on Qovery
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy on Qovery
        uses: Qovery/qovery-action@v0.10
        id: qovery
        with:
          qovery-organization-id: ${{ inputs.organization-id }}
          qovery-environment-id: ${{ inputs.environment-id }}
          qovery-application-ids: ${{ inputs.application-ids }}
          qovery-api-token: ${{ secrets.api-token }}