name: Deploy and Test on Qovery
on:
  workflow_call:
    inputs:
      organization-name:
        required: true
        type: string
      project-name:
        required: true
        type: string
      environment-name:
        required: true
        type: string
      application-names:
        required: true
        type: string
    secrets:
      api-token:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --configuration Release --no-restore
      - name: Run tests
        run: dotnet test --no-restore --verbosity minimal
  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy on Qovery
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy on Qovery
        uses: Qovery/qovery-action@v0.10
        id: qovery
        with:
          qovery-organization-name: ${{ inputs.organization-name }}
          qovery-project-name: ${{ inputs.project-name }}
          qovery-environment-name: ${{ inputs.environment-name }}
          qovery-application-names: ${{ inputs.application-names }}
          qovery-api-token: ${{ secrets.api-token }}